# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace # trims trailing whitespace
      - id: end-of-file-fixer # makes sure files end in a newline and only a newline.
      - id: check-yaml
      - id: check-added-large-files # no commit on large files
      - id: detect-private-key # detect private key
        # Prevent committing inline conflict markers
      - id: check-merge-conflict
        args: [ --assume-in-merge ]
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.14.1
    hooks:
      - id: markdown-link-check
        args: [ --quiet, "--config", ".config/markdown-lint-config.json" ]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.23.0
    hooks:
      # equivalent to:
      # commitlint --extends '@commitlint/config-conventional' --verbose --edit  "$1"
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-conventional' ]
        args: [ "--verbose" , "--config", ".config/commitlint.config.js" ]
  - repo: https://github.com/combostrap/repo-manager
    rev: 096af74
    hooks:
      - id: prevent-out-of-sync-commit
